// Generated by scripts/version-assets.mjs; commit with the release.
const RELEASE = {
  "version": "049831b9b8f4dca6",
  "assets": [
    {
      "path": "assets/ash-archer.svg",
      "hash": "7c7d6e9aaeea91b3"
    },
    {
      "path": "assets/bear.svg",
      "hash": "d1a927e8dd440f94"
    },
    {
      "path": "assets/boss.svg",
      "hash": "8c4cd8372fb6d4a2"
    },
    {
      "path": "assets/crypt-scarab.svg",
      "hash": "1b12a6801eac83d4"
    },
    {
      "path": "assets/demon.svg",
      "hash": "95a5282d679003e6"
    },
    {
      "path": "assets/druid.svg",
      "hash": "47459e487e9bcd95"
    },
    {
      "path": "assets/elemental.svg",
      "hash": "fcb204a14629340d"
    },
    {
      "path": "assets/equipment-body.svg",
      "hash": "9df0b002845ff23c"
    },
    {
      "path": "assets/equipment-slots.svg",
      "hash": "f1d9f97bb18d82ae"
    },
    {
      "path": "assets/frost-bat.svg",
      "hash": "c0ed22de57416254"
    },
    {
      "path": "assets/golem.svg",
      "hash": "15a07307ce209daa"
    },
    {
      "path": "assets/icon-16.svg",
      "hash": "8a427d37f106e15f"
    },
    {
      "path": "assets/icon-180.svg",
      "hash": "ceb7273a32a293b5"
    },
    {
      "path": "assets/icon-192.svg",
      "hash": "16aa1bc76c673115"
    },
    {
      "path": "assets/icon-32.svg",
      "hash": "dba4824a4f3913c8"
    },
    {
      "path": "assets/icon-512.svg",
      "hash": "3c519fe5176228c3"
    },
    {
      "path": "assets/icon-maskable.svg",
      "hash": "c11a1aa76efc5349"
    },
    {
      "path": "assets/icon.svg",
      "hash": "7b41c761a5cf9f2b"
    },
    {
      "path": "assets/necromancer.svg",
      "hash": "a5f032a35ac105f5"
    },
    {
      "path": "assets/nightreap-social.png",
      "hash": "857c719f3d5f6745"
    },
    {
      "path": "assets/nightreap-social.svg",
      "hash": "15cdc397c214bbc3"
    },
    {
      "path": "assets/ranger.svg",
      "hash": "7ea985e0e62c3984"
    },
    {
      "path": "assets/sanctuary-abyss.svg",
      "hash": "e6cd8d843fadf6b6"
    },
    {
      "path": "assets/sanctuary-crypt.svg",
      "hash": "99726bc9e420d069"
    },
    {
      "path": "assets/sanctuary-ember.svg",
      "hash": "45fdb119308705e2"
    },
    {
      "path": "assets/sanctuary-frost.svg",
      "hash": "5c2a27a62a4513ef"
    },
    {
      "path": "assets/sanctuary-wood.svg",
      "hash": "ebebe316293cb40a"
    },
    {
      "path": "assets/sheep.svg",
      "hash": "a33a363632658cdd"
    },
    {
      "path": "assets/skeleton.svg",
      "hash": "c75e92aed1d41004"
    },
    {
      "path": "assets/skills.svg",
      "hash": "59750d7c3dbfe6f5"
    },
    {
      "path": "assets/spore-stalker.svg",
      "hash": "fc5c60d71503834a"
    },
    {
      "path": "assets/terrain.svg",
      "hash": "dc817cb52aff7bb9"
    },
    {
      "path": "assets/title-scene.svg",
      "hash": "15db5f41acffe9c2"
    },
    {
      "path": "assets/void-colossus.svg",
      "hash": "426e234494bb5687"
    },
    {
      "path": "assets/void.svg",
      "hash": "752b604200b9956b"
    },
    {
      "path": "assets/warrior.svg",
      "hash": "7401f886ee91db51"
    },
    {
      "path": "assets/wizard.svg",
      "hash": "d0c8f830098328c6"
    },
    {
      "path": "assets/wolf.svg",
      "hash": "0892a875983f8e98"
    },
    {
      "path": "css/game.css",
      "hash": "41b14576a6a7dd93"
    },
    {
      "path": "favicon.ico",
      "hash": "1e1864e5f176f518"
    },
    {
      "path": "index.html",
      "hash": "adf20e19c9abcb94"
    },
    {
      "path": "manifest.webmanifest",
      "hash": "29a0d84bf2256812"
    },
    {
      "path": "src/core/audio.js",
      "hash": "3f8b4fd401f6503f"
    },
    {
      "path": "src/core/input.js",
      "hash": "eb9e1b198213da3e"
    },
    {
      "path": "src/core/loop.js",
      "hash": "6475da9477cdfb10"
    },
    {
      "path": "src/core/renderer.js",
      "hash": "d92da5f9ff2e2756"
    },
    {
      "path": "src/core/screenshot.js",
      "hash": "2ce5f207b47a042d"
    },
    {
      "path": "src/core/spatial.js",
      "hash": "4755d9a1200c721a"
    },
    {
      "path": "src/core/terrain-renderer.js",
      "hash": "bcaf4c99ad9db2cf"
    },
    {
      "path": "src/core/vector-image.js",
      "hash": "921478b13bcc057d"
    },
    {
      "path": "src/data/animation.js",
      "hash": "92ad9e820da9416a"
    },
    {
      "path": "src/data/audio.js",
      "hash": "09b125992cee5872"
    },
    {
      "path": "src/data/combat.js",
      "hash": "936ca80f602c3b09"
    },
    {
      "path": "src/data/config.js",
      "hash": "f28e6c5b4673f66a"
    },
    {
      "path": "src/data/gear.js",
      "hash": "dd3a72133bbc3a05"
    },
    {
      "path": "src/data/music/act0.json",
      "hash": "bc23ef2708008b06"
    },
    {
      "path": "src/data/music/act1.json",
      "hash": "6356e8f2e9b1a0c0"
    },
    {
      "path": "src/data/music/act2.json",
      "hash": "6d6e6f899f8e4e08"
    },
    {
      "path": "src/data/music/act3.json",
      "hash": "6cdba17726bfb1cd"
    },
    {
      "path": "src/data/music/act4.json",
      "hash": "d1fbfdbeeccf2ac3"
    },
    {
      "path": "src/data/music/boss.json",
      "hash": "d5e32b7a0f5acff2"
    },
    {
      "path": "src/data/music/dungeon.json",
      "hash": "63dc3fe1d38a89fd"
    },
    {
      "path": "src/data/music/index.json",
      "hash": "f429095ebf9f9a5c"
    },
    {
      "path": "src/data/music/menu.json",
      "hash": "0b80048198bedd06"
    },
    {
      "path": "src/data/music/sheep.json",
      "hash": "7f3123254c2bb954"
    },
    {
      "path": "src/data/music/town.json",
      "hash": "eb154257e94cf5f5"
    },
    {
      "path": "src/data/sanctuary.js",
      "hash": "27c83fc812468275"
    },
    {
      "path": "src/data/save.js",
      "hash": "2a952fa1ede7fff0"
    },
    {
      "path": "src/data/terrain.js",
      "hash": "a4d576ef9a3ef4e2"
    },
    {
      "path": "src/data/world.js",
      "hash": "ef5f78c241fd8cdd"
    },
    {
      "path": "src/main.js",
      "hash": "c13ce77a38f1013c"
    },
    {
      "path": "src/systems/combat.js",
      "hash": "3f2d9f692e326157"
    },
    {
      "path": "src/systems/exploration.js",
      "hash": "9c05b30176a59828"
    },
    {
      "path": "src/systems/gear.js",
      "hash": "45d026153c480c72"
    },
    {
      "path": "src/systems/i18n.js",
      "hash": "05f50c421756c74c"
    },
    {
      "path": "src/systems/pwa.js",
      "hash": "db9b2832dbced912"
    },
    {
      "path": "src/systems/save.js",
      "hash": "4faf8ce27f236bfb"
    },
    {
      "path": "src/systems/world.js",
      "hash": "5c31f3b40f67ee3b"
    }
  ]
};
