// Generated by scripts/version-assets.mjs; commit with the release.
const RELEASE = {
  "version": "14346379e8194b60",
  "assets": [
    {
      "path": "assets/characters/druid.svg",
      "hash": "b99e2b6fd9203f1a"
    },
    {
      "path": "assets/characters/necromancer.svg",
      "hash": "cffa5584e10008aa"
    },
    {
      "path": "assets/characters/ranger.svg",
      "hash": "a9af0919c79f96b7"
    },
    {
      "path": "assets/characters/warrior.svg",
      "hash": "4f15936d29741655"
    },
    {
      "path": "assets/characters/wizard.svg",
      "hash": "cfe05206f3f5f899"
    },
    {
      "path": "assets/corpses/abyss-lord.svg",
      "hash": "84621edfea1b9e96"
    },
    {
      "path": "assets/corpses/ash-archer.svg",
      "hash": "669c829a9b4a8412"
    },
    {
      "path": "assets/corpses/blight-matriarch.svg",
      "hash": "7de8b842f765dd69"
    },
    {
      "path": "assets/corpses/blighted-wolf.svg",
      "hash": "cf1a309fb711abea"
    },
    {
      "path": "assets/corpses/cinderling.svg",
      "hash": "c31b7780b801aafe"
    },
    {
      "path": "assets/corpses/crypt-scarab.svg",
      "hash": "950c4e690ace1566"
    },
    {
      "path": "assets/corpses/frost-bat.svg",
      "hash": "8a81867a6cfb897d"
    },
    {
      "path": "assets/corpses/frost-knight.svg",
      "hash": "6dc4d78602042895"
    },
    {
      "path": "assets/corpses/ghost.svg",
      "hash": "f21d9d0690a860fc"
    },
    {
      "path": "assets/corpses/glacial-herald.svg",
      "hash": "f4d6ce35e4a3835d"
    },
    {
      "path": "assets/corpses/grave-burrower.svg",
      "hash": "99b1721f8ea57e10"
    },
    {
      "path": "assets/corpses/hellhound.svg",
      "hash": "9fea68c804585b50"
    },
    {
      "path": "assets/corpses/ice-elemental.svg",
      "hash": "253d18faea4b591e"
    },
    {
      "path": "assets/corpses/imp.svg",
      "hash": "53303fb80a341f48"
    },
    {
      "path": "assets/corpses/infernal.svg",
      "hash": "f67e4a9a76d51605"
    },
    {
      "path": "assets/corpses/mourning-wraith.svg",
      "hash": "2fb2bafff36e7968"
    },
    {
      "path": "assets/corpses/parasite.svg",
      "hash": "a6ace50d5e3fc103"
    },
    {
      "path": "assets/corpses/pyre-warden.svg",
      "hash": "29e79a54986ba2de"
    },
    {
      "path": "assets/corpses/revenant.svg",
      "hash": "de2f6a570c9c3ec3"
    },
    {
      "path": "assets/corpses/sheep.svg",
      "hash": "97e0e93a2bd77f80"
    },
    {
      "path": "assets/corpses/skeletal-guard.svg",
      "hash": "a4ddbe53bfaa9f99"
    },
    {
      "path": "assets/corpses/snow-beast.svg",
      "hash": "f1fdc2d045cea065"
    },
    {
      "path": "assets/corpses/snow-oracle.svg",
      "hash": "98be79dba71d4a11"
    },
    {
      "path": "assets/corpses/spore-stalker.svg",
      "hash": "d335a9b96b9eb31e"
    },
    {
      "path": "assets/corpses/thorn-moth.svg",
      "hash": "08e5239d9eed0533"
    },
    {
      "path": "assets/corpses/treant.svg",
      "hash": "fbb3f72c65fb8606"
    },
    {
      "path": "assets/corpses/venom-spider.svg",
      "hash": "8317c5a2a0b70bd0"
    },
    {
      "path": "assets/corpses/void-colossus.svg",
      "hash": "8b1624ffbdde0de6"
    },
    {
      "path": "assets/corpses/void-tendril.svg",
      "hash": "99afc162791ecf3b"
    },
    {
      "path": "assets/corpses/zombie-mage.svg",
      "hash": "f13fc7688b59c2cf"
    },
    {
      "path": "assets/creatures/ash-archer.svg",
      "hash": "3c4058b33e6f84c6"
    },
    {
      "path": "assets/creatures/bear.svg",
      "hash": "c14f607d3585edc8"
    },
    {
      "path": "assets/creatures/boss.svg",
      "hash": "193f05627a1a094e"
    },
    {
      "path": "assets/creatures/crypt-scarab.svg",
      "hash": "0ef1cc0ef8aa03eb"
    },
    {
      "path": "assets/creatures/demon.svg",
      "hash": "f98b05802003dfcf"
    },
    {
      "path": "assets/creatures/elemental.svg",
      "hash": "4f8376053338daec"
    },
    {
      "path": "assets/creatures/frost-bat.svg",
      "hash": "0a83f717911d4955"
    },
    {
      "path": "assets/creatures/golem.svg",
      "hash": "ef7783f837647aea"
    },
    {
      "path": "assets/creatures/sheep.svg",
      "hash": "89f0914c86840f4e"
    },
    {
      "path": "assets/creatures/skeleton.svg",
      "hash": "e59a75ed3bf0603c"
    },
    {
      "path": "assets/creatures/spore-stalker.svg",
      "hash": "09f4452c4ffeb360"
    },
    {
      "path": "assets/creatures/void-colossus.svg",
      "hash": "9daead3bf20a52d3"
    },
    {
      "path": "assets/creatures/void.svg",
      "hash": "0ea83a7d000e8808"
    },
    {
      "path": "assets/creatures/wolf.svg",
      "hash": "9c1e30bd3c88f3c8"
    },
    {
      "path": "assets/icons/icon-16.svg",
      "hash": "42f6e2e8d9a3d160"
    },
    {
      "path": "assets/icons/icon-180.svg",
      "hash": "97036d268dab43b9"
    },
    {
      "path": "assets/icons/icon-192.svg",
      "hash": "a80bed70da9b71c1"
    },
    {
      "path": "assets/icons/icon-32.svg",
      "hash": "81ea4e02df29cb6a"
    },
    {
      "path": "assets/icons/icon-512.svg",
      "hash": "b9916bdf92342549"
    },
    {
      "path": "assets/icons/icon-maskable.svg",
      "hash": "1994e30c706d35df"
    },
    {
      "path": "assets/icons/icon.svg",
      "hash": "650283723d2cc24b"
    },
    {
      "path": "assets/sanctuaries/sanctuary-abyss.svg",
      "hash": "4d37755d1827a8eb"
    },
    {
      "path": "assets/sanctuaries/sanctuary-crypt.svg",
      "hash": "dca8bda292bbd7b1"
    },
    {
      "path": "assets/sanctuaries/sanctuary-ember.svg",
      "hash": "32d855ae55b0b863"
    },
    {
      "path": "assets/sanctuaries/sanctuary-frost.svg",
      "hash": "ff6b41184209ce05"
    },
    {
      "path": "assets/sanctuaries/sanctuary-wood.svg",
      "hash": "3b6d473bcf7344a1"
    },
    {
      "path": "assets/scenes/title-scene.svg",
      "hash": "3abe38ae392f963d"
    },
    {
      "path": "assets/social/nightreap-social.png",
      "hash": "2f3148a27360a7dd"
    },
    {
      "path": "assets/social/nightreap-social.svg",
      "hash": "0123a04faf934a8a"
    },
    {
      "path": "assets/terrain/terrain.svg",
      "hash": "c2f16dbecf21ab46"
    },
    {
      "path": "assets/ui/equipment-body.svg",
      "hash": "b9989a43ed2737c7"
    },
    {
      "path": "assets/ui/equipment-slots.svg",
      "hash": "2ffd3e1b243549ab"
    },
    {
      "path": "assets/ui/skills.svg",
      "hash": "6034a3433d5e0b9c"
    },
    {
      "path": "css/game.css",
      "hash": "934c80ab6987cf97"
    },
    {
      "path": "favicon.ico",
      "hash": "673cd28f84608d68"
    },
    {
      "path": "index.html",
      "hash": "65e2230ae1017bc7"
    },
    {
      "path": "manifest.webmanifest",
      "hash": "e19063b5bba040ed"
    },
    {
      "path": "src/core/audio.js",
      "hash": "9175c82b0ec34617"
    },
    {
      "path": "src/core/input.js",
      "hash": "eb9e1b198213da3e"
    },
    {
      "path": "src/core/loop.js",
      "hash": "6db24e1649c5b803"
    },
    {
      "path": "src/core/renderer.js",
      "hash": "e0bdcd6e34f4a136"
    },
    {
      "path": "src/core/screenshot.js",
      "hash": "2ce5f207b47a042d"
    },
    {
      "path": "src/core/spatial.js",
      "hash": "b86f8c37a13fe955"
    },
    {
      "path": "src/core/terrain-renderer.js",
      "hash": "794158c819350247"
    },
    {
      "path": "src/core/vector-image.js",
      "hash": "921478b13bcc057d"
    },
    {
      "path": "src/core/vfx-renderer.js",
      "hash": "069e607c0aa3cdb9"
    },
    {
      "path": "src/data/animation.js",
      "hash": "47b154d46c693913"
    },
    {
      "path": "src/data/audio.js",
      "hash": "c5e4578c00cd424f"
    },
    {
      "path": "src/data/combat.js",
      "hash": "fdc1129299fc0d36"
    },
    {
      "path": "src/data/config.js",
      "hash": "aa47ee4f503e4ac6"
    },
    {
      "path": "src/data/gear.js",
      "hash": "dd3a72133bbc3a05"
    },
    {
      "path": "src/data/music/act0-1.json",
      "hash": "da1115fa5f06b1c9"
    },
    {
      "path": "src/data/music/act0-2.json",
      "hash": "40dd5341d30561df"
    },
    {
      "path": "src/data/music/act0.json",
      "hash": "bc23ef2708008b06"
    },
    {
      "path": "src/data/music/act1-1.json",
      "hash": "405dbabc2737b04c"
    },
    {
      "path": "src/data/music/act1-2.json",
      "hash": "9d5524c59b892b9a"
    },
    {
      "path": "src/data/music/act1.json",
      "hash": "6356e8f2e9b1a0c0"
    },
    {
      "path": "src/data/music/act2-1.json",
      "hash": "efee14d6378f2761"
    },
    {
      "path": "src/data/music/act2-2.json",
      "hash": "35120e2bf62ed579"
    },
    {
      "path": "src/data/music/act2.json",
      "hash": "6d6e6f899f8e4e08"
    },
    {
      "path": "src/data/music/act3-1.json",
      "hash": "31bf130bc5745e0e"
    },
    {
      "path": "src/data/music/act3-2.json",
      "hash": "1752310587088b83"
    },
    {
      "path": "src/data/music/act3.json",
      "hash": "6cdba17726bfb1cd"
    },
    {
      "path": "src/data/music/act4-1.json",
      "hash": "78922991504fff45"
    },
    {
      "path": "src/data/music/act4-2.json",
      "hash": "7b635b5d6271ada8"
    },
    {
      "path": "src/data/music/act4.json",
      "hash": "d1fbfdbeeccf2ac3"
    },
    {
      "path": "src/data/music/boss.json",
      "hash": "d5e32b7a0f5acff2"
    },
    {
      "path": "src/data/music/dungeon.json",
      "hash": "63dc3fe1d38a89fd"
    },
    {
      "path": "src/data/music/index.json",
      "hash": "0b68072fc10b6d1d"
    },
    {
      "path": "src/data/music/menu.json",
      "hash": "0b80048198bedd06"
    },
    {
      "path": "src/data/music/sheep.json",
      "hash": "7f3123254c2bb954"
    },
    {
      "path": "src/data/music/town.json",
      "hash": "eb154257e94cf5f5"
    },
    {
      "path": "src/data/sanctuary.js",
      "hash": "27c83fc812468275"
    },
    {
      "path": "src/data/save.js",
      "hash": "2a952fa1ede7fff0"
    },
    {
      "path": "src/data/terrain.js",
      "hash": "a4d576ef9a3ef4e2"
    },
    {
      "path": "src/data/vfx.js",
      "hash": "22df8b0455347034"
    },
    {
      "path": "src/data/world.js",
      "hash": "ef5f78c241fd8cdd"
    },
    {
      "path": "src/main.js",
      "hash": "a468f9e1a0a247f6"
    },
    {
      "path": "src/systems/combat.js",
      "hash": "dbb7ada9bebd012a"
    },
    {
      "path": "src/systems/exploration.js",
      "hash": "9c05b30176a59828"
    },
    {
      "path": "src/systems/gear.js",
      "hash": "45d026153c480c72"
    },
    {
      "path": "src/systems/i18n.js",
      "hash": "e53b6131f86e52f9"
    },
    {
      "path": "src/systems/pwa.js",
      "hash": "db9b2832dbced912"
    },
    {
      "path": "src/systems/save.js",
      "hash": "4faf8ce27f236bfb"
    },
    {
      "path": "src/systems/world.js",
      "hash": "5c31f3b40f67ee3b"
    }
  ]
};
