// Generated by scripts/version-assets.mjs; commit with the release.
const RELEASE = {
  "version": "39a8cbf1966f8704",
  "assets": [
    {
      "path": "assets/bear.svg",
      "hash": "d1a927e8dd440f94"
    },
    {
      "path": "assets/boss.svg",
      "hash": "8c4cd8372fb6d4a2"
    },
    {
      "path": "assets/demon.svg",
      "hash": "95a5282d679003e6"
    },
    {
      "path": "assets/druid.svg",
      "hash": "47459e487e9bcd95"
    },
    {
      "path": "assets/elemental.svg",
      "hash": "fcb204a14629340d"
    },
    {
      "path": "assets/equipment-body.svg",
      "hash": "9df0b002845ff23c"
    },
    {
      "path": "assets/equipment-slots.svg",
      "hash": "f1d9f97bb18d82ae"
    },
    {
      "path": "assets/golem.svg",
      "hash": "15a07307ce209daa"
    },
    {
      "path": "assets/icon-16.svg",
      "hash": "8a427d37f106e15f"
    },
    {
      "path": "assets/icon-180.svg",
      "hash": "ceb7273a32a293b5"
    },
    {
      "path": "assets/icon-192.svg",
      "hash": "16aa1bc76c673115"
    },
    {
      "path": "assets/icon-32.svg",
      "hash": "dba4824a4f3913c8"
    },
    {
      "path": "assets/icon-512.svg",
      "hash": "3c519fe5176228c3"
    },
    {
      "path": "assets/icon-maskable.svg",
      "hash": "c11a1aa76efc5349"
    },
    {
      "path": "assets/icon.svg",
      "hash": "7b41c761a5cf9f2b"
    },
    {
      "path": "assets/necromancer.svg",
      "hash": "a5f032a35ac105f5"
    },
    {
      "path": "assets/ranger.svg",
      "hash": "7ea985e0e62c3984"
    },
    {
      "path": "assets/sanctuary-abyss.svg",
      "hash": "e6cd8d843fadf6b6"
    },
    {
      "path": "assets/sanctuary-crypt.svg",
      "hash": "99726bc9e420d069"
    },
    {
      "path": "assets/sanctuary-ember.svg",
      "hash": "45fdb119308705e2"
    },
    {
      "path": "assets/sanctuary-frost.svg",
      "hash": "5c2a27a62a4513ef"
    },
    {
      "path": "assets/sanctuary-wood.svg",
      "hash": "ebebe316293cb40a"
    },
    {
      "path": "assets/sheep.svg",
      "hash": "a33a363632658cdd"
    },
    {
      "path": "assets/skeleton.svg",
      "hash": "c75e92aed1d41004"
    },
    {
      "path": "assets/skills.svg",
      "hash": "59750d7c3dbfe6f5"
    },
    {
      "path": "assets/terrain.svg",
      "hash": "dc817cb52aff7bb9"
    },
    {
      "path": "assets/title-scene.svg",
      "hash": "15db5f41acffe9c2"
    },
    {
      "path": "assets/void.svg",
      "hash": "752b604200b9956b"
    },
    {
      "path": "assets/warrior.svg",
      "hash": "7401f886ee91db51"
    },
    {
      "path": "assets/wizard.svg",
      "hash": "d0c8f830098328c6"
    },
    {
      "path": "assets/wolf.svg",
      "hash": "0892a875983f8e98"
    },
    {
      "path": "css/game.css",
      "hash": "5075451ae5a5be4d"
    },
    {
      "path": "favicon.ico",
      "hash": "1e1864e5f176f518"
    },
    {
      "path": "index.html",
      "hash": "921eb614118132ce"
    },
    {
      "path": "manifest.webmanifest",
      "hash": "29a0d84bf2256812"
    },
    {
      "path": "src/core/audio.js",
      "hash": "2be6495cc07963c9"
    },
    {
      "path": "src/core/input.js",
      "hash": "eb9e1b198213da3e"
    },
    {
      "path": "src/core/loop.js",
      "hash": "d6afbf4fc767ffde"
    },
    {
      "path": "src/core/renderer.js",
      "hash": "82e3d93a56ccb450"
    },
    {
      "path": "src/core/spatial.js",
      "hash": "74cbf7213b824da4"
    },
    {
      "path": "src/core/terrain-renderer.js",
      "hash": "fa54c2b9186e698c"
    },
    {
      "path": "src/data/animation.js",
      "hash": "ee8f6f7a081853ea"
    },
    {
      "path": "src/data/audio.js",
      "hash": "241a8ba752e8b994"
    },
    {
      "path": "src/data/combat.js",
      "hash": "936ca80f602c3b09"
    },
    {
      "path": "src/data/config.js",
      "hash": "0bc99017d137590b"
    },
    {
      "path": "src/data/gear.js",
      "hash": "dd3a72133bbc3a05"
    },
    {
      "path": "src/data/sanctuary.js",
      "hash": "27c83fc812468275"
    },
    {
      "path": "src/data/save.js",
      "hash": "459c3b474f9babff"
    },
    {
      "path": "src/data/terrain.js",
      "hash": "a4d576ef9a3ef4e2"
    },
    {
      "path": "src/data/world.js",
      "hash": "bea1f47a1d00e4e4"
    },
    {
      "path": "src/main.js",
      "hash": "b363d0947c30dba6"
    },
    {
      "path": "src/systems/combat.js",
      "hash": "f1e3b7531e2bb6a3"
    },
    {
      "path": "src/systems/exploration.js",
      "hash": "9c05b30176a59828"
    },
    {
      "path": "src/systems/gear.js",
      "hash": "eb46dd9db95cfb0f"
    },
    {
      "path": "src/systems/i18n.js",
      "hash": "05f50c421756c74c"
    },
    {
      "path": "src/systems/pwa.js",
      "hash": "db9b2832dbced912"
    },
    {
      "path": "src/systems/save.js",
      "hash": "0fc28909b3cdaba8"
    },
    {
      "path": "src/systems/world.js",
      "hash": "51b61829a8005c30"
    }
  ]
};
