import { createHash } from 'node:crypto';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { dirname, resolve, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

// Release maintenance only: checked-in ES modules run directly without this command.
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const hash = content => createHash('sha256').update(content).digest('hex').slice(0, 16);
const hashes = new Map();
const visiting = new Set();
const localPath = (owner, reference) => posix.normalize(posix.join(posix.dirname(owner), reference.split(/[?#]/)[0]));
async function save(path, content) {
  const target = resolve(root, path);
  if (await readFile(target, 'utf8').catch(() => null) !== content) await writeFile(target, content);
}
async function version(path) {
  if (hashes.has(path)) return hashes.get(path);
  if (path.endsWith('.ico') || path.endsWith('.png')) {
    const digest = hash(await readFile(resolve(root, path)));
    hashes.set(path, digest);
    return digest;
  }
  if (visiting.has(path)) throw new Error(`Cyclic version dependency: ${path}`);
  visiting.add(path);
  let content = await readFile(resolve(root, path), 'utf8');
  if (path === 'src/data/music/index.json') {
    const entries = JSON.parse(content);
    for (const [scene, file] of Object.entries(entries)) {
      const base = file.split('?')[0];
      if (base !== `${scene}.json`) throw new Error(`Music filename must match scene: ${scene}`);
      entries[scene] = `${base}?v=${await version(posix.join(posix.dirname(path), base))}`;
    }
    content = JSON.stringify(entries, null, 2) + '\n';
    await save(path, content);
  }
  const matches = path.endsWith('.js')
    ? [...content.matchAll(/(?:\bfrom\s+|new URL\()(['"])(\.\.?\/[^'"]+)\1/g)]
    : path.endsWith('.css') ? [...content.matchAll(/url\((['"])(\.\.?\/[^'"]+)\1\)/g)] : [];
  for (const match of matches.reverse()) {
    const reference = match[2];
    const dependency = localPath(path, reference);
    const digest = await version(dependency);
    const base = reference.split(/[?#]/)[0];
    const fragment = reference.includes('#') ? '#' + reference.split('#')[1] : '';
    const replacement = match[0].replace(reference, `${base}?v=${digest}${fragment}`);
    content = content.slice(0, match.index) + replacement + content.slice(match.index + match[0].length);
  }
  if (matches.length) await save(path, content);
  const digest = hash(content);
  hashes.set(path, digest);
  visiting.delete(path);
  return digest;
}
async function files(directory) {
  const result = [];
  for (const entry of await readdir(resolve(root, directory), { withFileTypes: true })) {
    const path = posix.join(directory, entry.name);
    if (entry.isDirectory()) result.push(...await files(path));
    else if (/\.(js|css|svg|json|png)$/.test(entry.name)) result.push(path);
  }
  return result;
}
const assets = ['favicon.ico', ...await files('src'), ...await files('css'), ...await files('assets')].sort();
for (const path of assets) await version(path);
const manifest = JSON.parse(await readFile(resolve(root, 'manifest.webmanifest'), 'utf8'));
for (const icon of manifest.icons) {
  const path = icon.src.split('?')[0];
  icon.src = `${path}?v=${await version(path)}`;
}
await save('manifest.webmanifest', JSON.stringify(manifest, null, 2) + '\n');
await version('manifest.webmanifest');
let html = await readFile(resolve(root, 'index.html'), 'utf8');
for (const match of [...html.matchAll(/\b(?:src|href)="((?:assets\/|css\/|src\/|manifest\.webmanifest|favicon\.ico)[^"]*)"/g)].reverse()) {
  const path = match[1].split('?')[0];
  const replacement = match[0].replace(match[1], `${path}?v=${await version(path)}`);
  html = html.slice(0, match.index) + replacement + html.slice(match.index + match[0].length);
}
await save('index.html', html);
await version('index.html');
const entries = [...hashes].map(([path, hash]) => ({ path, hash })).sort((a, b) => a.path.localeCompare(b.path));
const worker = await readFile(resolve(root, 'sw.js'), 'utf8');
const workerIdentity = worker.replace(/importScripts\('\.\/sw-assets\.js(?:\?v=[^']+)?'\);/, "importScripts('./sw-assets.js');");
const release = { version: hash(JSON.stringify(entries) + workerIdentity), assets: entries };
const inventory = `// Generated by scripts/version-assets.mjs; commit with the release.\nconst RELEASE = ${JSON.stringify(release, null, 2)};\n`;
await save('sw-assets.js', inventory);
await save('sw.js', worker.replace(/importScripts\('\.\/sw-assets\.js(?:\?v=[^']+)?'\);/, `importScripts('./sw-assets.js?v=${hash(inventory)}');`));
console.log(`Versioned ${entries.length} assets; release ${release.version}`);
